=== LibreOffice/core/package/dtd/Manifest.dtd
<!--
 * This file is part of the Collabora Office project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 -->
<!ELEMENT manifest:manifest (manifest:file-entry+)>
<!ATTLIST manifest:manifest xmlns:manifest CDATA #FIXED "http://openoffice.org/2001/manifest"> 

<!ELEMENT manifest:file-entry (manifest:encryption-data?)>
<!-- manifest:size is usually only specified for encrypted entries -->
<!ATTLIST manifest:file-entry
	manifest:full-path CDATA #REQUIRED
	manifest:size CDATA #IMPLIED
	manifest:media-type CDATA #REQUIRED
>

<!ELEMENT manifest:encryption-data (manifest:algorithm,manifest:key-derivation)>
<!ATTLIST manifest:encryption-data
	manifest:checksum-type CDATA #REQUIRED
	manifest:checksum CDATA #REQUIRED >
<!-- algorithm-name specifies the name of the algorithm used to encrypt
	 the stream, for example Blowfish 
	 manifest:initialisation-vector is stored encoded in Base64 -->
<!ELEMENT manifest:algorithm EMPTY>
<!ATTLIST manifest:algorithm
	manifest:algorithm-name CDATA #REQUIRED
	manifest:initialisation-vector CDATA #REQUIRED>

<!ELEMENT manifest:key-derivation EMPTY>
<!-- manifest:key-derivation-name specifies the name of the algorithm used to derive
	 the key, for example PBKDF2 (see rfc 2898 ) 
	 manifest:salt is stored encoded in Base64 -->
<!ATTLIST manifest:key-derivation
	manifest:key-derivation-name CDATA #REQUIRED
	manifest:salt CDATA #REQUIRED
	manifest:iteration-count CDATA #REQUIRED>

=== LibreOffice/core/extras/source/autotext/lang/sv/standard/META-INF/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifest:manifest PUBLIC "-//OpenOffice.org//DTD Manifest 1.0//EN" "../../../../../../../package/dtd/Manifest.dtd">
<manifest:manifest xmlns:manifest="http://openoffice.org/2001/manifest">
 <manifest:file-entry manifest:full-path="/" manifest:media-type=""/>
 <manifest:file-entry manifest:full-path="O/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="O/O.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANY/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANY/ANY.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="OR/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="OR/OR.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="MVH/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="MVH/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="MVH/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="MVH/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="MVH/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="UA/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="UA/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="UA/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="UA/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="UA/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P1/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P1/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P1/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P1/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P1/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P2/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P2/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P2/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P2/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="P2/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ABM/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ABM/ABM.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="LOREM/LOREM.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="FN/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="FN/Object_1/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="FN/Object_1/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="FN/Object_1/" manifest:media-type="application/vnd.oasis.opendocument.formula"/>
 <manifest:file-entry manifest:full-path="FN/manifest.rdf" manifest:media-type="application/rdf+xml"/>
 <manifest:file-entry manifest:full-path="FN/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="FN/" manifest:media-type="application/vnd.oasis.opendocument.text"/>
 <manifest:file-entry manifest:full-path="UL/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="UL/UL.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="BT/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="BT/BT.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="B/B.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="BV/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="BV/BV.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AA/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AA/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AA/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AA/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AA/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="BlockList.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="F/F.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANS/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANS/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANS/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANS/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="ANS/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AI/meta.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AI/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AI/settings.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AI/content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="AI/styles.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="K/atevent.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="K/K.xml" manifest:media-type="text/xml"/>
</manifest:manifest>
